### ISSUE TITLE
Include axios as dependency

### ISSUE THREAD

**Issue by nival999** [simpleledger/BitcoinFilesJS#10]
Axios is not included as a dependency in the package.json, but is used in ./lib/bitdb.js

This is failing in a Webpack build downstream because Webpack will always try to require something like that

**Comment by projectoblio** [comment]
i think the correct location for the bitbox dependency is as a "peer dependency" as well. It is technically not a dev dependency, and peer dependencies basically issue a console warning that say: "if this package (bitcoinfiles) is part of another library, we will be using that library's bitbox. otherwise, please install bitbox!"

**Comment by jcramer** [comment]
Closing since bitdb is no longer supported.
